export const CREATOR_LIST_REQUEST = 'CREATOR_LIST_REQUEST'
export const CREATOR_LIST_SUCCESS = 'CREATOR_LIST_SUCCESS'
export const CREATOR_LIST_FAIL = 'CREATOR_LIST_FAIL'



export const CREATOR_DETAILS_REQUEST = 'CREATOR_DETAILS_REQUEST'
export const CREATOR_DETAILS_SUCCESS = 'CREATOR_DETAILS_SUCCESS'
export const CREATOR_DETAILS_FAIL = 'CREATOR_DETAILS_FAIL'