# Generated by Django 4.1.4 on 2023-02-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_creator_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='image',
        ),
    ]
