# Generated by Django 4.1.4 on 2023-03-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_creatorpricelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyordershare',
            name='order_type',
            field=models.CharField(default='BUY', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='sellordershare',
            name='order_type',
            field=models.CharField(default='SELL', editable=False, max_length=10),
        ),
    ]
