# Generated by Django 4.1.4 on 2023-02-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_creator_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
