# Generated by Django 4.1.4 on 2023-02-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_creator_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='yt_id',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
