# Generated by Django 4.1.4 on 2023-03-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_creator_yt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorshare',
            name='in_transit',
            field=models.BooleanField(default=False),
        ),
    ]
