# Generated by Django 4.1.4 on 2023-04-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_buyordershare_order_type_sellordershare_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyordershare',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='sellordershare',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
