# Generated by Django 4.1.4 on 2023-04-16 02:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_buyordershare_quantity_sellordershare_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyordershare',
            name='shares_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='sellordershare',
            name='shares_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
    ]
