# Generated by Django 4.1.4 on 2023-04-16 02:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_buyordershare_shares_list_sellordershare_shares_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellordershare',
            name='shares_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
